# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkmDJpH2ZNKwDZgsk4A3GvHln4Z51pMr
"""

# Kutubxonalarni import qilish
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

# 1. Audio faylni yuklash
audio_path = 'bass2.wav'  # Update with the correct file path
# If the audio file is not in the same directory as your notebook,
# you need to specify the full path to the file.
try:
    y, sr = librosa.load(audio_path, sr=None)   # Audio signal va namunaviy chastota
except librosa.exceptions.NoBackendError:
    print(f"Error: Could not open file '{audio_path}'. Please make sure the file exists and is in a supported format.")
    # Add any additional error handling here, like exiting the script
    # or trying a different audio file
    exit(1) # Example: Exit with an error code
except FileNotFoundError:
    print(f"Error: File '{audio_path}' not found.")
    exit(1)

# 2. Spektrogramma generatsiyasi
# Qisqa muddatli Fourier o'zgarishi (STFT) dan foydalanamiz
D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)

# 3. Vizualizatsiya qilish
plt.figure(figsize=(12, 6))
librosa.display.specshow(D, sr=sr, x_axis='time', y_axis='log', cmap='viridis')
plt.colorbar(format='%+2.0f dB')
plt.title('Spektragramma')
plt.xlabel('Vaqt (s)')
plt.ylabel('Chastota (Hz)')
plt.tight_layout()
plt.show()

# Kutubxonalarni import qilish
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

# 1. Audio faylni yuklash
audio_path = 'bass.wav'  # Update with the correct file path
# If the audio file is not in the same directory as your notebook,
# you need to specify the full path to the file.
try:
    y, sr = librosa.load(audio_path, sr=None)   # Audio signal va namunaviy chastota
except librosa.exceptions.NoBackendError:
    print(f"Error: Could not open file '{audio_path}'. Please make sure the file exists and is in a supported format.")
    # Add any additional error handling here, like exiting the script
    # or trying a different audio file
    exit(1) # Example: Exit with an error code
except FileNotFoundError:
    print(f"Error: File '{audio_path}' not found.")
    exit(1)

# 2. Spektrogramma generatsiyasi
# Qisqa muddatli Fourier o'zgarishi (STFT) dan foydalanamiz
D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)

# 3. Vizualizatsiya qilish
plt.figure(figsize=(12, 6))
librosa.display.specshow(D, sr=sr, x_axis='time', y_axis='log', cmap='viridis')
plt.colorbar(format='%+2.0f dB')
plt.title('Spektragramma')
plt.xlabel('Vaqt (s)')
plt.ylabel('Chastota (Hz)')
plt.tight_layout()
plt.show()

# Kutubxonalarni import qilish
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

# 1. Audio faylni yuklash
audio_path = 'bass3.wav'  # Update with the correct file path
# If the audio file is not in the same directory as your notebook,
# you need to specify the full path to the file.
try:
    y, sr = librosa.load(audio_path, sr=None)   # Audio signal va namunaviy chastota
except librosa.exceptions.NoBackendError:
    print(f"Error: Could not open file '{audio_path}'. Please make sure the file exists and is in a supported format.")
    # Add any additional error handling here, like exiting the script
    # or trying a different audio file
    exit(1) # Example: Exit with an error code
except FileNotFoundError:
    print(f"Error: File '{audio_path}' not found.")
    exit(1)

# 2. Spektrogramma generatsiyasi
# Qisqa muddatli Fourier o'zgarishi (STFT) dan foydalanamiz
D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)

# 3. Vizualizatsiya qilish
plt.figure(figsize=(12, 6))
librosa.display.specshow(D, sr=sr, x_axis='time', y_axis='log', cmap='viridis')
plt.colorbar(format='%+2.0f dB')
plt.title('Spektragramma')
plt.xlabel('Vaqt (s)')
plt.ylabel('Chastota (Hz)')
plt.tight_layout()
plt.show()

!pip install gtts

from gtts import gTTS
import os

# Matnni belgilash
text = "Assalomu aleykum Ozodbek xush kelibsiz"

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os

# Matnni belgilash
text = "Sizga qanday yordam bera olaman"

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os

# Matnni belgilash
text = "Tanishganimdan xursandman!"

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)